# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3763722019969f10a32b882c66f291b713c26cb3607e03a2aaed65fb0f3583afcd9259b66b6c4444efb780fd1f15af452e0bdd532cfa2fec70693f57e6766bf5

test:
  secret_key_base: b8f48e9cbdfe726737a29e9c028e0a86202cc1887b68fbd866c7fe04d8daf1e3edd5d88e146fc97846770455e74e7bd02a27bad978a818ba49a33a7632d085cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
